name: Update submodule
description: Automatically update submodule
inputs:
  user:
    description: The GitHub API user
    required: true
  token:
    description: The GitHub API token to use
    required: true
  repo:
    description: The Remote Repo
    required: true
  repo_owner:
    description: The Remote Repo Owner
    required: true
  committor_username:
    description: Commitor Username
    required: true
  committor_email:
    description: Commitor Email
    required: true
  path:
    description: Submodule path
    required: true
branding:
  icon: anchor
  color: purple
runs:
  using: 'node16'
  main: 'dist/index.js'